// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsNlu5SA-cPBhH_NWXSUkSGsr7_FreUAM',
    appId: '1:445384516686:web:dd99edd0dae6090138cf1f',
    messagingSenderId: '445384516686',
    projectId: 'eduassist-48217',
    authDomain: 'eduassist-48217.firebaseapp.com',
    storageBucket: 'eduassist-48217.firebasestorage.app',
    measurementId: 'G-JEE4D0L4H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnz-m7Efcy0-3kuWgqHVn0EunKiKVXhc',
    appId: '1:445384516686:android:df1929fb1ea664e638cf1f',
    messagingSenderId: '445384516686',
    projectId: 'eduassist-48217',
    storageBucket: 'eduassist-48217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2rCxt_4Hcs1LL811RZHL7K3znkJUZYpE',
    appId: '1:445384516686:ios:b83008f215d02fb238cf1f',
    messagingSenderId: '445384516686',
    projectId: 'eduassist-48217',
    storageBucket: 'eduassist-48217.firebasestorage.app',
    iosBundleId: 'com.example.eduassistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsNlu5SA-cPBhH_NWXSUkSGsr7_FreUAM',
    appId: '1:445384516686:web:041ab6e979e63fc838cf1f',
    messagingSenderId: '445384516686',
    projectId: 'eduassist-48217',
    authDomain: 'eduassist-48217.firebaseapp.com',
    storageBucket: 'eduassist-48217.firebasestorage.app',
    measurementId: 'G-K31TN02J93',
  );
}
